questions=[
	{"Which group supported American independence?":{"Wrong":"Tories", "Right":"Whigs"}},
  {"Who said: \"Give me liberty or give me death!\"?":{"Wrong":"Paul Revere","Right":"Patrick Henry"}},
  {"Who was the Commander in Chief of the Continental Army?":{"Wrong":"Thomas Jefferson","Right":"George Washington"}},
  {"What was the call for peace written to King George called?":{"Wrong":"Apple Tree Petition","Right":"Olive Branch Petition"}},
  {"Who wrote the pamphlet: \"Common Sense\"?":{"Wrong":"Ben Franklin","Right":"Thomas Paine"}},
  {"Who was the American ambassador to France?":{"Wrong":"Thomas Jefferson","Right":"Ben Franklin"}},
  {"What was the treaty that ended the Revolutionary War?":{"Wrong":"Treaty of Versailles","Right":"Treaty of Paris"}},
  {"Which country aided America in the war?":{"Wrong":"Spain","Right":"France"}},
  {"Who was defeated at the Battle of Yorktown?":{"Wrong":"Robert E. Lee","Right":"Charles Cornwallis"}},
  {"What was significant about the date of the Battle of Trenton?":{"Wrong":"4th of July","Right":"Christmas Day"}},
  {"Who did George III hire to fight the Americans?":{"Wrong":"The Prussians","Right":"The Hessians"}},
  {"What battle was the \"turning point\" of the war?":{"Wrong":"Bunker Hill","Right":"Saratoga"}},
  {"What cultural movement directly inspired the Revolution?":{"Wrong":"The Renaissance","Right":"The Enlightenment"}},
  {"What was Nathan Hale's profession?":{"Wrong":"Pastor","Right":"Teacher"}},
  {"What faction did the majority of colonists align with?":{"Wrong":"Loyalists","Right":"Patriots"}},
  {"Who made the infamous \"Midnight Ride\"?":{"Wrong":"Paul Revere","Right":"Sam Prescott"}},
]
